from abc import ABC, abstractmethod

class SocketHandler(ABC):
    @abstractmethod
    def bind(self, address: str) -> None: ...
    @abstractmethod
    def recvfrom(self, bufsize: int): ...
    @abstractmethod
    def sendto(self, data: bytes, address: str): ...
    @abstractmethod
    def close(self): ...